# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HDAnimationTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HDAnimationTest
  pod 'pop', '~> 1.0'
  pod 'SnapKit'
  
  target 'HDAnimationTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HDAnimationTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
